# ----
# Site
url: "https://babi.wildanfauzy.com"
baseurl: "https://babi.wildanfauzy.com"
title: Kandang Babi
logo: /siteicon.png
description: Dunia Babi dan Seisinya.
author: 
  name: Wildan Fauzy
  email:
  twitter: wilfauzy # twitter username without the @ symbol
social:
  name: 
  links:
    - https://github.com/wilfauzy

# -----
# Build

timezone: Etc/UTC

exclude:
  - README.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "full.html"
    values:
      layout: "chapters"
      toc: "hash"

collections:
  chapters:
    output: true
  extras:
